name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROVAR_HOME: ${{ github.workspace }}/ProvarHome

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Run build
      run: |
        mkdir $GITHUB_WORKSPACE/ProvarHome
        curl -O https://download.provartesting.com/latest/Provar_ANT_latest.zip
        unzip -o Provar_ANT_latest.zip -d ProvarHome
        rm Provar_ANT_latest.zip
        sudo apt-get update && sudo apt-get upgrade
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >>sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y install google-chrome-stable
        sudo add-apt-repository ppa:mozillateam/firefox-next && sudo apt install firefox
        echo $PROVAR_HOME
        cd $GITHUB_WORKSPACE/proj1/ANT
        xvfb-run ant -f /home/runner/work/URLTest/URLTest/proj1/ANT/build.xml

    - uses: actions/upload-artifact@v2
      with:
        name: Execution Report
        path: ${{ github.workspace }}/proj1/ANT/Results/*

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Failed Execution Report
        path: ${{ github.workspace }}/proj1/ANT/Results/*
